default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: salman@123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: library_website_development

test:
  <<: *default
  database: library_website_test

production:
  <<: *default
  database: db/production.sqlite3